### ISSUE TITLE
Problem with oauth.d.ts: module has no default export

### ISSUE THREAD

**Issue by jeffhuys** [evert/ketting#113]
I guess this is more of a question than an actual issue, so bear with me.

With our `tsconfig.json` (see at the bottom of this issue), we get the following error: `ERROR in node_modules/ketting/dist/utils/oauth.d.ts(1,8): error TS1192: Module '"$WORKING_DIR/node_modules/client-oauth2/index"' has no default export.`.

The line in question is as follows: `import ClientOAuth2 from 'client-oauth2';`.  
When we change it to `import * as ClientOAuth2 from 'client-oauth2';`, everything works as expected.

Is this something in our `tsconfig.json`, is this something you can change, or is it something that's out of your hands?

Our `tsconfig.json`:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

Thank you for your time (and this awesome library ;))

**Comment by jeffhuys** [comment]
Hey @evert,

This does make sense, but I think you didn't understand me correctly. Please tell me if I understood *you* wrong, but the error doesn't seem to be in our code; it's in the `ketting` package, right after install. In the file `node_modules/ketting/dist/utils/oauth.d.ts` exists this line of code: `import ClientOAuth2 from 'client-oauth2';`, which throws the error. It's not a big deal to change it, and also not *that* big of a deal to include the change in our CI scripts, but if we can fix it (by either changing the tsconfig or making a pull request), that would be preferrable. 

Did I understand you wrong, and is this actually by design?

Thanks for your time. :+1:

**Comment by evert** [comment]
Ok, that's really weird! I wonder if you have a different version of `client-oauth2`. I'm not having this problem myself.

**Comment by 9days** [comment]
"compilerOptions": {
...
"esModuleInterop": true
...
}

**Comment by evert** [comment]
Interesting. Do you think it's better if we have that setting off by default?

**Comment by nseney1** [comment]
Hey all. I'm having this issue as well. Any progress?

**Comment by jeffhuys** [comment]
Just for the record, my `client-oauth2` version: `"client-oauth2": "^4.2.1"`

**Comment by evert** [comment]
So it sounds like `esModuleInterop` is the key for people to fix this. This is set in the `tsconfig.json` for this project, and removing this setting does cause a number of errors to pop up.

So if you add `esModuleInterop` to your own `tsconfig.json` this error _should_ go away. What I'm just just certain of is: does it make sense for this project to remove `esModuleInterop` ?

**Comment by evert** [comment]
I have a PR and I don't think there's any reason not to merge this. If it makes this lib more compatible with people's environment, can't hurt.

**Comment by evert** [comment]
This is now released
