### ISSUE TITLE
Normalize Location Header

### ISSUE THREAD

**Issue by LarsKoelpin** [evert/ketting#125]
Hi, 
I'm running a spring stack webapp, which generates Headers with uppercase
("location" vs "Location") which of course do not equal.

https://github.com/evert/ketting/blob/ba064b60a3698cbc309e6b2b2c31c6dfba6ceb8d/src/resource.ts#L143

I think it is needed to normallize the headers first, before doing the logic.
I got around the issue by normalizing the string inline using

```javascript  
if (Object.keys(response.headers).map(val => val.toLowerCase()).indexOf('location' != -1)) {
            return this.go(response.headers.get('Location')); // problematic
        }
```
Which of couse is not the best solution too, as I still need to access the correct case.

sincerly

**Comment by evert** [comment]
Hi Lars,

Since HTTP headers are not case sensitive, the ’fetch‘ library should actually already handle this.

What environment are you running this?

**Comment by LarsKoelpin** [comment]
Yeah your totatally right.
I guess it was a setup bug on my side. Cannot reproduce the issue.

Closing for now
