### ISSUE TITLE
Support `credentials` param.

### ISSUE THREAD

**Issue by enrique-ramirez** [evert/ketting#50]
Hi!

This library is looking good! I have a use-case where I need to pass cookies to the request. [This is done by passing `credentials: 'include'` to the `fetch` options](https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending_credentials_with_a_fetch_request). 

I was wondering if this is something you are planning on supporting? I have a first attempt on a fork at the moment, but I'm unsure if it'd be the right approach or if it collides with OAUth 2 or Basic Auth and, if so, how it should be handled.

**Comment by evert** [comment]
Hi @enrique-ramirez ,

This sounds like a good idea. I think the right approach is to allow a list of fetch settings to be passed in the `options` argument.
