### ISSUE TITLE
Representation.Follow("link")

### ISSUE THREAD

**Issue by perploug** [evert/ketting#54]
Hi 

Wonderful library - been a joy to use, one question tho: 

After a resource is fetched as a representation (complete with _links and _embedded) is there a way to do representation.follow("link") - so I can call links on the representation (without getting them from _links manually) 

/Per

**Comment by evert** [comment]
Hi @perploug ,

The intention with the current API is that you are supposed to follow a link from a resource, not a representation. However, I'm curious if there's a specific use-case you have in mind that I might have missed.

In my case at least, `follow` on a resource is always all I ever need, but maybe you're seeing something I'm not seeing.

**Comment by perploug** [comment]
I use it to render pages from a cms - and in some cases, I would like to also fetch children of a page, 

So first I get the page, then want to follow its "children" link to get a collection of child pages - and I have that information on the representation, but still have to go back to the resource and do the .follow() - so its a minor thing, I can work around it, was just wondering if I had missed anything obvious.

**Comment by evert** [comment]
No you didn't miss something. I'm a little hesitant still to add something like this, unless I have a bit more data about what people need. I think eventually I kind of see the representation object more as an implementation detail, and not something I expect people to directly interact with. It's more intended as a cacheable object that simply holds all data in case another GET request is made...

I'm still not super sure though, but I wanna keep an eye on it.
